name: PDrill
main: me.devcom.pdrill.PDrill
version: 0.3.2
description: >
             Bukkit programable drill plugin.
commands:
  pdscript:
    description: PDrill script command
    usage: /pdscript <drillId> <script <...>>
  pdload:
    description: PDrill script load command
    usage: /pdload <drillId> <script_name>
  pdcreate:
    description: Create new [scripts / fuels]
    usage: /pdcreate <script | fuel> <name> [script]
  pddelete:
    description: Delete [scripts / fuels]
    usage: /pddelete <script | fuel> <name>
  pdchange:
    description: Change settings for [scripts / fuels]
    usage: /pdchange <script | fuel> <name> <setting_name> <val>
  pdlist:
    description: List [scripts / fuels / drills]
    usage: /pdlist <script | fuel | drill>
  pdmake:
    description: Loads advanced / predefined script
    usage: /pdmake <name> <args>
  pdlink:
    description: Links drills
    usage: /pdlink <drillId> <fuel_name>
  pddelink:
    description: Dedinks drills
    usage: /pddelink <drillId>
  pdplace:
    description: Add new placer to drill
    usage: /pdplace <drillId> <place_interval> <place_direction>
    
permissions:
    pd.*:
        description: Gives access to all PDrill commands
        children:
            pd.use: true
    pd.use:
        description: Allows you to use PDrill
        default: true
